[package]
name = "web-server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { workspace = true, features = ["rustls-0_23"] }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
